name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Build packages
        run: pnpm build:packages
      
      - name: Run tests
        run: pnpm test
      
      - name: Type check
        run: pnpm type-check
      
      - name: Lint
        run: pnpm lint

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for content processing

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Build shared packages
        run: pnpm build:packages
      
      - name: Process content
        run: pnpm build:content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build blog with admin
        run: pnpm build:blog
        env:
          NODE_ENV: production
          VITE_SITE_URL: https://wpti.dev
          VITE_SITE_TITLE: "When Pressure Turns into Inspiration"
          VITE_SITE_DESCRIPTION: "When Pressure Turns into Inspiration"
          VITE_AUTHOR_NAME: "JQ"
          VITE_AUTHOR_EMAIL: "jqyu.lee@gmail.com"
          VITE_POSTS_PER_PAGE: 10
          VITE_FEATURED_POSTS_COUNT: 3
          VITE_GITHUB_REPO: ${{ github.repository }}
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/blog/dist
          # Uncomment and configure if using custom domain
          # cname: yourdomain.com

  lighthouse-audit:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v4
      - name: Wait for deployment
        run: sleep 30
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://${{ github.repository_owner }}.github.io
            https://${{ github.repository_owner }}.github.io/posts
          uploadArtifacts: true